In [1]:
import torch
import numpy as np

In [2]:
# 定义函数，使用指定数据创建张量
def dm01():
    # 场景1 标量 张量
    t1 = torch.tensor(5)
    print(f"t1: {t1}, dtype: {type(t1)}")
    print('-' * 50)

    # 场景2 二维列表装换为张量
    data = [[1, 2, 3], [4, 5, 6]]
    t2 = torch.tensor(data)
    print(f"t2: {t2}, dtype: {type(t2)}")
    print('-' * 50)

    # 场景3 numpy数组转换为张量
    data1 = np.random.randint(0, 10, (2, 3))
    t3 = torch.tensor(data1, dtype=torch.float)
    print(f"t3: {t3}, dtype: {type(t3)}")

dm01()

t1: 5, dtype: <class 'torch.Tensor'>
--------------------------------------------------
t2: tensor([[1, 2, 3],
        [4, 5, 6]]), dtype: <class 'torch.Tensor'>
--------------------------------------------------
t3: tensor([[3., 0., 4.],
        [1., 8., 8.]]), dtype: <class 'torch.Tensor'>


In [3]:
# 场景1：torch.ones 和 torch.ones_like 创建一个全1张量
t1 = torch.ones(2, 3)       # 创建一个2行3列的全1张量
print(f"t1: {t1}, type: {type(t1)}")
print('-' * 50)

t2 = torch.tensor([[1,2], [3,4], [5,6]])

t3 = torch.ones_like(t2)
print(f"t3: {t3}, type: {type(t3)}")
print('-' * 50)


# 场景2：torch.zeros 和 torch.zeros_like 创建一个全0张量
t4 = torch.zeros(2, 3)       # 创建一个2行3列的全1张量
print(f"t4: {t4}, type: {type(t4)}")
print('-' * 50)

t5 = torch.tensor([[1,2], [3,4], [5,6]])

t6 = torch.zeros_like(t5)
print(f"t3: {t6}, type: {type(t6)}")
print('-' * 50)

# 场景3：torch.full 和 torch.full_like 创建一个指定值的张量
t7 = torch.full((2, 3), 255)       # 创建一个2行3列的全5张量
print(f"t7: {t7}, type: {type(t7)}")
print('-' * 50)

t8 = torch.tensor([[1,2], [3,4], [5,6]])
t9 = torch.full_like(t8, 255)
print(f"t9: {t9}, type: {type(t9)}")

t1: tensor([[1., 1., 1.],
        [1., 1., 1.]]), type: <class 'torch.Tensor'>
--------------------------------------------------
t3: tensor([[1, 1],
        [1, 1],
        [1, 1]]), type: <class 'torch.Tensor'>
--------------------------------------------------
t4: tensor([[0., 0., 0.],
        [0., 0., 0.]]), type: <class 'torch.Tensor'>
--------------------------------------------------
t3: tensor([[0, 0],
        [0, 0],
        [0, 0]]), type: <class 'torch.Tensor'>
--------------------------------------------------
t7: tensor([[255, 255, 255],
        [255, 255, 255]]), type: <class 'torch.Tensor'>
--------------------------------------------------
t9: tensor([[255, 255],
        [255, 255],
        [255, 255]]), type: <class 'torch.Tensor'>


创建线性张量和随机张量

In [5]:
# 1- 创建线性张量
def dm01():
    # 创建一个从0到9的步长为2的线性张量
    t1 = torch.arange(0, 10, 2)
    print(f"t1: {t1}, dtype: {type(t1)}")
    print('-' * 50)

    t2 = torch.linspace(1, 10, 10)
    print(f"t2: {t2}, dtype: {type(t2)}")
    print('-' * 50)

dm01()

t1: tensor([0, 2, 4, 6, 8]), dtype: <class 'torch.Tensor'>
--------------------------------------------------
t2: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), dtype: <class 'torch.Tensor'>
--------------------------------------------------


In [6]:
# 2- 定义函数，创建随机张量
def dm02():
    # 设置随机种子，确保每次生成的随机数相同
    # torch.manual_seed(3)   # 设置随机固定种子
    torch.initial_seed()     # 时间戳作为随机种子

    # 创建随机张量
    t1 = torch.rand(size=(2, 3))
    print(f"t1: {t1}, dtype: {type(t1)}")
    print('-' * 50)

    # 创建随机整数张量
    t2 = torch.randint(0, 10, size=(3, 5))
    print(f"t2: {t2}, dtype: {type(t2)}")
    print('-' * 50)

dm02()

t1: tensor([[0.8022, 0.4205, 0.6663],
        [0.6501, 0.6005, 0.4893]]), dtype: <class 'torch.Tensor'>
--------------------------------------------------
t2: tensor([[4, 6, 7, 6, 2],
        [1, 3, 4, 2, 7],
        [5, 4, 5, 8, 3]]), dtype: <class 'torch.Tensor'>
--------------------------------------------------


张量的数据类型转换

In [7]:
# 场景1：直接创建指定类型张量
t1 = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print(f"t1: {t1}, 元素类型：{t1.dtype}, type: {type(t1)}")
print('-' * 50)

# 场景2：从已有张量转换类型
# 1- 方式一：使用type()方法(优先使用这种)
t2 = t1.type(torch.int32)
print(f"t2: {t2}, 元素类型：{t2.dtype}, type: {type(t2)}")
print('-' * 50)

# 方式二：使用half()方法/double()方法等
t3 = t2.half()          # 转换为float16类型
t4 = t3.double()        # 转换为float64类型
t5 = t4.float()         # 转换为float32类型
print(f"t3: {t3}, 元素类型：{t3.dtype}, type: {type(t3)}")
print(f"t4: {t4}, 元素类型：{t4.dtype}, type: {type(t4)}")
print(f"t5: {t5}, 元素类型：{t5.dtype}, type: {type(t5)}")

t1: tensor([1., 2., 3., 4., 5.]), 元素类型：torch.float32, type: <class 'torch.Tensor'>
--------------------------------------------------
t2: tensor([1, 2, 3, 4, 5], dtype=torch.int32), 元素类型：torch.int32, type: <class 'torch.Tensor'>
--------------------------------------------------
t3: tensor([1., 2., 3., 4., 5.], dtype=torch.float16), 元素类型：torch.float16, type: <class 'torch.Tensor'>
t4: tensor([1., 2., 3., 4., 5.], dtype=torch.float64), 元素类型：torch.float64, type: <class 'torch.Tensor'>
t5: tensor([1., 2., 3., 4., 5.]), 元素类型：torch.float32, type: <class 'torch.Tensor'>


张量与numpy数组的相互转换及基本运算
    常用场景总结：

        场景1：张量转为numpy数组
            张量对象.numpy()                   共享内存
            张量对象.numpy().copy()            不共享内存,链式编程写法
        场景2：numpy数组转为张量
            torch.from_numpy()                 共享内存
            torch.tensor()                     不共享内存
        场景3：从标量张量中提取其内容
            从标量张量.item()

        重点掌握的：
            张量对象.numpy()
            torch.tensor(nd数组)
            从标量张量提取内容 标量张量.item()

    张量基本运算总结：
        add()、sub()、mul()、div()      张量的加减乘除运算
        add_()、sub_()、mul_()、div_()  带下划线的会修改原张量（就地操作）

In [8]:
# 场景1：张量转为numpy数组
def dm01():
    # 1- 创建张量
    t1 = torch.tensor([1, 2, 3])
    print(f"t1: {t1}, dtype: {type(t1)}")

    # 2- 张量转为numpy数组
    nda = t1.numpy().copy()     # 不共享内存
    n1 = t1.numpy()  # 共享内存

    # 3- 打印结果，测试是否共享内存
    n1[0] = 100
    print(f"nda: {nda}")
    print(f"n1: {n1}")
    print(f"t1: {t1}")
    print("-" * 50)

# 场景2：numpy数组转为张量
def dm02():
    t1 = torch.tensor(np.array([1, 2, 3]))
    print(f"t1: {t1}, dtype: {type(t1)}")
    print("-" * 50)

# 场景3：从标量张量中提取其内容
def dm03():
    t1 = torch.tensor(10)
    print(f"t1: {t1.item()}, dtype: {type(t1.item())}")

dm01(), dm02(), dm03()

t1: tensor([1, 2, 3]), dtype: <class 'torch.Tensor'>
nda: [1 2 3]
n1: [100   2   3]
t1: tensor([100,   2,   3])
--------------------------------------------------
t1: tensor([1, 2, 3]), dtype: <class 'torch.Tensor'>
--------------------------------------------------
t1: 10, dtype: <class 'int'>


(None, None, None)

In [9]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
# 1- 张量的加法
t3 = t1.add(t2)
print(f"t1 + t2: {t3}")

t4 = t1 + t2
print(f"t1 + t2: {t4}")
print("-" * 50)

# 2- 张量的减法
t5 = t1.sub(t2)
print(f"t1 - t2: {t5}")

t6 = t1 - t2
print(f"t1 - t2: {t6}")
print("-" * 50)

# 3- 张量的乘法
t7 = t1.mul(t2)
print(f"t1 * t2: {t7}")

t8 = t1 * t2
print(f"t1 * t2: {t8}")
print("-" * 50)

# 4- 张量的除法
t9 = t1.div(t2)
print(f"t1 / t2: {t9}")

t10 = t1 / t2
print(f"t1 / t2: {t10}")
print("-" * 50)

# 5- 取反
t11 = -t1
print(f"-t1: {t11}")

t12 = t1.neg()
print(f"-t1: {t12}")
print("-" * 50)

t1 + t2: tensor([5, 7, 9])
t1 + t2: tensor([5, 7, 9])
--------------------------------------------------
t1 - t2: tensor([-3, -3, -3])
t1 - t2: tensor([-3, -3, -3])
--------------------------------------------------
t1 * t2: tensor([ 4, 10, 18])
t1 * t2: tensor([ 4, 10, 18])
--------------------------------------------------
t1 / t2: tensor([0.2500, 0.4000, 0.5000])
t1 / t2: tensor([0.2500, 0.4000, 0.5000])
--------------------------------------------------
-t1: tensor([-1, -2, -3])
-t1: tensor([-1, -2, -3])
--------------------------------------------------


    张量的点乘和矩阵乘法
    点乘：
        api：
            t1 * t2
            t1.mul(t2)

    矩阵乘法：
        api:
            t1 @ t2
            t1.matmul(t2)
            t1.dot(t2)

In [10]:
def dm01():
    # 1- 创建两个个两行三列的张量
    t01 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    print(f"t01: {t01}")

    t02 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    print(f"t02: {t02}")

    # 2- 点乘
    # t03 = t01.mul(t02)
    t03 = t01 * t02
    print(f"t01 * t02: {t03}")
    print("-" * 50)

dm01()

t01: tensor([[1, 2, 3],
        [4, 5, 6]])
t02: tensor([[1, 2, 3],
        [4, 5, 6]])
t01 * t02: tensor([[ 1,  4,  9],
        [16, 25, 36]])
--------------------------------------------------


In [11]:
# 定义函数，矩阵乘法
def dm02():
    # 1- 创建2x3的张量
    t04 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    print(f"t01: {t04}")

    # 2- 创建3x2的张量
    t05 = torch.tensor([[1, 2], [3, 4], [5, 6]])
    print(f"t02: {t05}")

    # 3- 矩阵乘法
    t06 = t04.matmul(t05)
    # t03 = t03 @ t04
    print(f"t01 * t02: {t06}")

dm02()

t01: tensor([[1, 2, 3],
        [4, 5, 6]])
t02: tensor([[1, 2],
        [3, 4],
        [5, 6]])
t01 * t02: tensor([[22, 28],
        [49, 64]])


张量常用运算函数

In [12]:
# 1- 定义2x3张量
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)

# 2- 按不同维度计算张量的值
# 2.1- 求和
print(f"t1.sum(): {t1.sum()}")                  # 整体求和
print(f"t1.sum(dim=0): {t1.sum(dim=0)}")        # 按行求和
print(f"t1.sum(dim=1): {t1.sum(dim=1)}")        # 按列求和
print("-" * 50)

# 2.2 求最大值
print(f"t1.max(): {t1.max()}")
print(f"t1.max(dim=0): {t1.max(dim=0)}")
print(f"t1.max(dim=1): {t1.max(dim=1)}")
print("-" * 50)

# 2.3 求最小值
print(f"t1.min(): {t1.min()}")
print(f"t1.min(dim=0): {t1.min(dim=0)}")
print(f"t1.min(dim=1): {t1.min(dim=1)}")
print("-" * 50)

# 2.4 求均值
print(f"t1.mean(): {t1.mean()}")
print(f"t1.mean(dim=0): {t1.mean(dim=0)}")
print(f"t1.mean(dim=1): {t1.mean(dim=1)}")

t1.sum(): 21.0
t1.sum(dim=0): tensor([5., 7., 9.])
t1.sum(dim=1): tensor([ 6., 15.])
--------------------------------------------------
t1.max(): 6.0
t1.max(dim=0): torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
t1.max(dim=1): torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))
--------------------------------------------------
t1.min(): 1.0
t1.min(dim=0): torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
t1.min(dim=1): torch.return_types.min(
values=tensor([1., 4.]),
indices=tensor([0, 0]))
--------------------------------------------------
t1.mean(): 3.5
t1.mean(dim=0): tensor([2.5000, 3.5000, 4.5000])
t1.mean(dim=1): tensor([2., 5.])


张量的索引操作

In [13]:
# 1- 设置随机种子
torch.manual_seed(24)

# 2- 创建张量
t1 = torch.randint(1, 10, (5, 5))
print(f"t1: {t1}")
print('-' * 50)

# 3- 索引操作
# 场景1：简单行列索引
print(t1[1])        # 获取第二行
print(t1[1, :])     # 等价于上面一行
print('-' * 50)
print(t1[:, 1])     # 获取第二列
print('-' * 50)

# 场景2：列表索引
# 1) 获取(0, 1)和(1, 2)两个位置的元素
print(t1[[0, 1], [1, 2]])

# 2) 获取(1, 2)和(3, 4)两个位置的元素   注：第一个列表表示行索引，第二个列表表示列索引
print(t1[[1, 3], [2, 4]])
print('-' * 50)

# 3) 获取第0、1行的第1、2列元素
print(t1[[0, 1], 1:3])
print('-' * 50)
print(t1[[[0], [1]], [1, 2]])
print('-' * 50)

# 场景3：范围索引
# 1) 获取前三行，前两列的数据
print(t1[:3, :2])

# 2) 获取第2到最后一行，前两列数据
print(t1[2:, :2])

# 3) 获取所有奇数行，偶数列的数据
print(t1[1::2, ::2])
print('-' * 50)

# 场景4：布尔索引
# 1) 获取第三列大于5数据的行
print(t1[t1[:, 2] > 5])
print("-" * 50)

# 2) 获取第二行大于5的列数据
# 注意明确要取的是行、行元素、还是列
"""
    t1[t1[1, :] > 5]: 把返回的列索引列表作为行索引传入, 获取到的是行
    t1[1, t1[1, :] > 5]: 把返回的列索引列表作为列索引传入, 第一个参数传入的是指定行, 获取值指定行满足条件的值
    t1[: ,t1[1, :] > 5]: 把返回的列索引列表作为列索引传入, 第一个参数为: , 获取值所有行中满足条件的列
"""
print(t1[: ,t1[1, :] > 5])
print(t1[t1[1, :] > 5])
print(t1[1, t1[1, :] > 5])
print(t1[1, :] > 5)
print('-' * 50)


# 场景5：多维索引
# 创建三维向量
t2 = torch.randint(1, 10, (2, 3, 4))
print(f't2: {t2}')
print('-' * 50)

# 1) 获取0轴上的第一个数据
print(t2[0, :, :])

# 2) 获取1轴上的第一个数据
print(t2[:, 0, :])

# 3) 获取2轴上的第一个数据
print(t2[:, :, 0])

t1: tensor([[6, 9, 9, 2, 8],
        [7, 8, 5, 8, 4],
        [7, 4, 3, 9, 3],
        [6, 1, 4, 2, 8],
        [1, 2, 5, 7, 4]])
--------------------------------------------------
tensor([7, 8, 5, 8, 4])
tensor([7, 8, 5, 8, 4])
--------------------------------------------------
tensor([9, 8, 4, 1, 2])
--------------------------------------------------
tensor([9, 5])
tensor([5, 8])
--------------------------------------------------
tensor([[9, 9],
        [8, 5]])
--------------------------------------------------
tensor([[9, 9],
        [8, 5]])
--------------------------------------------------
tensor([[6, 9],
        [7, 8],
        [7, 4]])
tensor([[7, 4],
        [6, 1],
        [1, 2]])
tensor([[7, 5, 4],
        [6, 4, 8]])
--------------------------------------------------
tensor([[6, 9, 9, 2, 8]])
--------------------------------------------------
tensor([[6, 9, 2],
        [7, 8, 8],
        [7, 4, 9],
        [6, 1, 2],
        [1, 2, 7]])
tensor([[6, 9, 9, 2, 8],
        [7

张量的形状操作

    API总结：
        张量的形状操作：
                    reshape(): 在不改变张量内容的前提下，对其形状做出改变
                    squeeze(): 降维，删除所有为1的维度
                    unsqueeze(): 升维，在指定位置增加一个维度，值为1
                    transpose(): 一次只能交换2个维度
                    permute(): 一次同时交换多个维度
                    contiguous()： 返回一个内存连续的张量拷贝，保证张量在内存中是按行优先存储的
                    view()： 在不改变张量内容的前提下，对其形状做出改变，要求张量在内存中是连续存储的

In [14]:
# 1- 定义函数，应用reshape()函数
def dm01():
    # 创建2x3张量
    t1 = torch.randint(1, 10, (2, 3))
    print(f"t1: {t1}, shape: {t1.shape}, row: {t1.shape[0]}, colomn: {t1.shape[1]}")

    t2 = t1.reshape(3, 2)
    print(f"t2: {t2}, shape: {t2.shape}, row: {t2.shape[0]}, colomn: {t2.shape[1]}")

dm01()

t1: tensor([[2, 6, 3],
        [2, 3, 7]]), shape: torch.Size([2, 3]), row: 2, colomn: 3
t2: tensor([[2, 6],
        [3, 2],
        [3, 7]]), shape: torch.Size([3, 2]), row: 3, colomn: 2


In [15]:
# 2- 创建函数，应用unsqueeze()函数和squeeze()函数
def dm02():
    t1 = torch.randint(1, 10, size=(2, 3))
    print(f"t1: {t1}, shape: {t1.shape}, row: {t1.shape[0]}, colomn: {t1.shape[1]}")

    # 在0维度增加一个维度
    t2 = t1.unsqueeze(0)
    print(f"t2: {t2}, shape: {t2.shape}")      # (1, 2, 3)

    # 在1维度增加一个维度
    t3 = t1.unsqueeze(1)
    print(f"t3: {t3}, shape: {t3.shape}")       # (2, 1, 3)

    # 在2维度增加一个维度
    t4 = t1.unsqueeze(2)
    print(f"t4: {t4}, shape: {t4.shape}")       # (2, 3, 1)

    # # 在3维度增加一个维度
    # t5 = t1.unsqueeze(3)                        # 报错
    # print(f"t5: {t5}, shape: {t5.shape}")       # (2, 3, ?, 1)

    # 删除所有为1的维度
    t6 = torch.randint(1, 10, size=(2, 1, 3, 1, 1))
    print(f"t6: {t6}, shape: {t6.shape}")

    t7 = t6.squeeze()
    print(f"t7: {t7}, shape: {t7.shape}")

dm02()

t1: tensor([[5, 1, 7],
        [9, 2, 3]]), shape: torch.Size([2, 3]), row: 2, colomn: 3
t2: tensor([[[5, 1, 7],
         [9, 2, 3]]]), shape: torch.Size([1, 2, 3])
t3: tensor([[[5, 1, 7]],

        [[9, 2, 3]]]), shape: torch.Size([2, 1, 3])
t4: tensor([[[5],
         [1],
         [7]],

        [[9],
         [2],
         [3]]]), shape: torch.Size([2, 3, 1])
t6: tensor([[[[[1]],

          [[9]],

          [[6]]]],



        [[[[8]],

          [[5]],

          [[7]]]]]), shape: torch.Size([2, 1, 3, 1, 1])
t7: tensor([[1, 9, 6],
        [8, 5, 7]]), shape: torch.Size([2, 3])


In [16]:
# 定义函数，应用transpose()函数和permute()函数
def dm03():
    t1 = torch.randint(1, 10, size=(2, 3, 4))
    print(f"t1: {t1}, shape: {t1.shape}")
    print('-' * 50)

    # 交换0和1两个维度
    t2 = t1.transpose(0, 1)
    print(f"t2: {t2}, shape: {t2.shape}")
    print('-' * 50)

    # 交换0和2两个维度
    t3 = t1.transpose(0, 2)
    print(f"t3: {t3}, shape: {t3.shape}")
    t4 = t1.transpose(0, -1)            # 等价与t3
    print(f"t4: {t4}, shape: {t4.shape}")

    # (2, 3, 4) -> (3, 4, 2)
    t5 = t1.permute(1, 2, 0)
    print(f"t5: {t5}, shape: {t5.shape}")

dm03()

t1: tensor([[[5, 8, 5, 9],
         [5, 6, 2, 1],
         [3, 9, 8, 7]],

        [[1, 6, 5, 3],
         [8, 3, 8, 8],
         [1, 8, 9, 4]]]), shape: torch.Size([2, 3, 4])
--------------------------------------------------
t2: tensor([[[5, 8, 5, 9],
         [1, 6, 5, 3]],

        [[5, 6, 2, 1],
         [8, 3, 8, 8]],

        [[3, 9, 8, 7],
         [1, 8, 9, 4]]]), shape: torch.Size([3, 2, 4])
--------------------------------------------------
t3: tensor([[[5, 1],
         [5, 8],
         [3, 1]],

        [[8, 6],
         [6, 3],
         [9, 8]],

        [[5, 5],
         [2, 8],
         [8, 9]],

        [[9, 3],
         [1, 8],
         [7, 4]]]), shape: torch.Size([4, 3, 2])
t4: tensor([[[5, 1],
         [5, 8],
         [3, 1]],

        [[8, 6],
         [6, 3],
         [9, 8]],

        [[5, 5],
         [2, 8],
         [8, 9]],

        [[9, 3],
         [1, 8],
         [7, 4]]]), shape: torch.Size([4, 3, 2])
t5: tensor([[[5, 1],
         [8, 6],
         [5, 5

In [17]:
def dm04():
    t1 = torch.randint(1, 10, size=(2, 3))
    print(f"t1: {t1}, shape: {t1.shape}")

    # 判断张量是否连续存储, 即张量中的顺序 和 内存中的存储顺序一致
    print(t1.is_contiguous())

    t2 = t1.view(3, 2)
    print(f"t2: {t2}, shape: {t2.shape}")
    print(t2.is_contiguous())

    t3 = t1.transpose(0, 1)
    print(f"t3: {t3}, shape: {t3.shape}")
    print(t3.is_contiguous())

    # t4 = t3.view(2, 3)      # 报错
    # print(f"t4: {t4}, shape: {t4.shape}")
    # print(t4.is_contiguous())

    # 将t3转换为连续存储
    t4 = t3.contiguous()
    print(f"t4: {t4}, shape: {t4.shape}")
    print(t4.is_contiguous())

dm04()

t1: tensor([[3, 8, 6],
        [1, 4, 6]]), shape: torch.Size([2, 3])
True
t2: tensor([[3, 8],
        [6, 1],
        [4, 6]]), shape: torch.Size([3, 2])
True
t3: tensor([[3, 1],
        [8, 4],
        [6, 6]]), shape: torch.Size([3, 2])
False
t4: tensor([[3, 1],
        [8, 4],
        [6, 6]]), shape: torch.Size([3, 2])
True


张量的拼接与堆叠

    API总结：
        cat(): 不改变维度数，除了拼接的维度上，其他维度必须相同，
        stack(): 改变维度数，所有维度必须相同

In [24]:
# 1- 创建两个张量
t1 = torch.randint(1, 10, (2, 3))
print(f"t1: {t1}, shape: {t1.shape}")

t2 = torch.randint(1, 10, (2, 3))
print(f"t2: {t2}, shape: {t2.shape}")

t1: tensor([[5, 6, 8],
        [8, 6, 5]]), shape: torch.Size([2, 3])
t2: tensor([[7, 3, 8],
        [4, 8, 4]]), shape: torch.Size([2, 3])


In [23]:
# 2- cat()函数拼接张量
t3 = torch.cat([t1, t2], dim=0)
print(f"t3: {t3}, shape: {t3.shape}")

t4 = torch.cat([t1, t2], dim=1)
print(f"t4: {t4}, shape: {t4.shape}")

t3: tensor([[2, 3, 5],
        [3, 7, 2],
        [8, 3, 6],
        [8, 6, 3]]), shape: torch.Size([4, 3])
t4: tensor([[2, 3, 5, 8, 3, 6],
        [3, 7, 2, 8, 6, 3]]), shape: torch.Size([2, 6])


In [22]:
# 3- stack()函数拼接张量
t5 = torch.stack([t1, t2], dim=0)
print(f"t5: {t5}, shape: {t5.shape}")

t6 = torch.stack([t1, t2], dim=1)
print(f"t6: {t6}, shape: {t6.shape}")

t7 = torch.stack([t1, t2], dim=2)
print(f"t7: {t7}, shape: {t7.shape}")

t5: tensor([[[2, 3, 5],
         [3, 7, 2]],

        [[8, 3, 6],
         [8, 6, 3]]]), shape: torch.Size([2, 2, 3])
t6: tensor([[[2, 3, 5],
         [8, 3, 6]],

        [[3, 7, 2],
         [8, 6, 3]]]), shape: torch.Size([2, 2, 3])
t7: tensor([[[2, 8],
         [3, 3],
         [5, 6]],

        [[3, 8],
         [7, 6],
         [2, 3]]]), shape: torch.Size([2, 3, 2])


自动微分模块

    权重更新公式:
        w新 = w旧 - 学习率 * 梯度
        梯度 = 损失函数的导数

In [26]:
# 1- 定义变量，记录初始权重参数
w = torch.tensor(10, requires_grad=True, dtype=torch.float)

# 2- 定义损失函数
loss = 2 * w ** 2

# # 3- 打印梯度函数类型(了解)
# print(f"损失函数的类型为: {type(loss.grad_fn)}")

# 4- 反向传播，计算梯度 => 损失函数的导数
loss.sum().backward()    # 保证loss是一个标量

# 5- 带入权重更新公式，计算新的权重参数
w.data = w.data - 0.01 * w.grad

# 6- 打印最终结果
print(f"最终结果为: {w}")

最终结果为: 9.600000381469727


自动微分模块demo, 使用梯度下降法，迭代100次，求最优解

In [27]:
# 1- 初始化权重参数和定义损失函数
w = torch.tensor(10, requires_grad=True, dtype=torch.float)

loss = w ** 2 + 20

# 2- 利用梯度下降法，迭代100次，求最优解
print(f"开始权重初始值为: {w}, (0.01 * w.grad): 无, loss: {loss}")

# 迭代100次，求最优解
for i in range(1, 101):
    # 2.1- 正向计算（前向传播）
    loss = w ** 2 + 20

    # 2.2- 梯度清零
    if w.grad is not None:
        w.grad.zero_()

    # 2.3- 反向传播，计算梯度
    loss.sum().backward()

    # 2.4- 权重更新
    w.data = w.data - 0.01 * w.grad

    # 2.5- 打印每次迭代结果
    print(f"第{i}次迭代，权重更新为: {w}, (0.01 * w.grad): {0.01 * w.grad}, loss: {loss: .5f}")

# 3- 打印最终结果
print(f"最终结果为: {w}, 梯度: {w.grad}, loss: {loss: .5f}")

开始权重初始值为: 10.0, (0.01 * w.grad): 无, loss: 120.0
第1次迭代，权重更新为: 9.800000190734863, (0.01 * w.grad): 0.19999998807907104, loss:  120.00000
第2次迭代，权重更新为: 9.604000091552734, (0.01 * w.grad): 0.19599999487400055, loss:  116.04000
第3次迭代，权重更新为: 9.411920547485352, (0.01 * w.grad): 0.19207999110221863, loss:  112.23682
第4次迭代，权重更新为: 9.223682403564453, (0.01 * w.grad): 0.18823841214179993, loss:  108.58425
第5次迭代，权重更新为: 9.03920841217041, (0.01 * w.grad): 0.1844736486673355, loss:  105.07632
第6次迭代，权重更新为: 8.858424186706543, (0.01 * w.grad): 0.1807841658592224, loss:  101.70729
第7次迭代，权重更新为: 8.681255340576172, (0.01 * w.grad): 0.17716847360134125, loss:  98.47168
第8次迭代，权重更新为: 8.507630348205566, (0.01 * w.grad): 0.17362509667873383, loss:  95.36420
第9次迭代，权重更新为: 8.337477684020996, (0.01 * w.grad): 0.17015260457992554, loss:  92.37978
第10次迭代，权重更新为: 8.170727729797363, (0.01 * w.grad): 0.16674955189228058, loss:  89.51353
第11次迭代，权重更新为: 8.007312774658203, (0.01 * w.grad): 0.16341455280780792, loss:  86.76079
第

需要注意的问题：自动微分不能直接转numpy数组，会报错。 需要使用detach()函数，拷贝一份张量，然后再转为numpy数组

In [31]:
# 1- 定义张量
t1 = torch.tensor([10, 20], requires_grad=True, dtype=torch.float)
print(f"t1: {t1}, dtype: {type(t1)}")

# 2- 尝试把上述张量转为numpy数组
# t1_numpy = t1.numpy()       # 会报错，原因是t1张量是需要计算梯度的张量，不能直接转为numpy数组

# 正确做法: 使用detach()函数，拷贝一份张量，然后再转为numpy数组
t2 = t1.detach().numpy()
print(f"t2: {t2}, dtype: {type(t2)}")

# 3- 测试上述的t1和t2是否共享同一块空间
t1.data[0] = 100
print(f"t1: {t1}, type: {type(t2)}")
print(f"t2: {t2}, type: {type(t2)}")


# # 4- 查看t1和t2的谁可以自动微分
# print(f"t1: {t1.requires_grad}")      # True
# print(f"t2: {t2.requires_grad}")      #  False

t1: tensor([10., 20.], requires_grad=True), dtype: <class 'torch.Tensor'>
t2: [10. 20.], dtype: <class 'numpy.ndarray'>
t1: tensor([100.,  20.], requires_grad=True), type: <class 'numpy.ndarray'>
t2: [100.  20.], type: <class 'numpy.ndarray'>


自动微分综合demo, 模拟线性回归的训练过程

In [34]:
import torch
from torch.utils.data import TensorDataset, DataLoader
from torch import nn, optim
from sklearn.datasets import make_regression
import matplotlib.pyplot as plt

plt.rcParams['font.sans-serif'] = ['SimHei']        # 用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False          # 解决负号显示为方块的问题

def create_dataset():
    # 1- 创建数据集对象
    x, y, coef = make_regression(
        n_samples=100,
        n_features=1,
        noise=10.0,
        coef=True,
        bias=14.5,
        random_state=3
    )
    # 2- 把上述数据封装成张量对象
    x = torch.tensor(x, dtype=torch.float32)
    y = torch.tensor(y, dtype=torch.float32)

    # 3- 返回结果
    return x, y, coef

def train(x, y, coef):
    # 1- 创建数据集对象,tensor -> 数据集对象 -> 数据加载器
    dataset = TensorDataset(x, y)

    # 2- 创建数据加载器对象
    # 参1：数据集对象  参2：批次大小  参3：是否打乱数据
    dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

    # 3- 创建初始的线性回归模型
    # 参1：输入特征维度  参2：输出特征维度
    model = nn.Linear(1, 1)

    # 4- 创建损失函数
    criterion = nn.MSELoss()

    # 5- 创建优化器
    # 参1：待优化的参数  参2：学习率(learning rate) -> lr
    optimizer = optim.SGD(model.parameters(), lr=0.01)

    # 6- 训练模型
    # 6.1- 定义变量，分别表示训练轮数、每轮的（平均）损失值、训练总损失值、训练样本数
    epochs, loss_list, total_loss, total_sample = 100, [], 0.0, 0
    # 6.2- 开始训练
    for epoch in range(epochs):
        # 6.3- 每轮是分批次训练的，所以从数据加载器中获取数据
        for x_train, y_train in dataloader:
            # 6.4- 模型预测
            y_pred = model(x_train)
            # 6.5- 计算损失
            loss = criterion(y_pred, y_train.reshape(-1, 1))
            # 6.6- 计算总损失和样本批次
            total_loss += loss.item()
            total_sample += 1
            # 6.7- 反向传播，计算梯度 并更新参数
            optimizer.zero_grad()           # 梯度清零
            loss.sum().backward()           #

        # 6.8 把本轮的（平均）损失值，添加到列表中
        loss_list.append(total_loss / total_sample)
        print(f"第{epoch + 1}轮迭代，总损失为: {total_loss / total_sample: .5f}")

    # 7- 打印最终结果
    print(f"{epochs}轮的平均损失分别为: {loss_list}")


# 1- 创建数据集
x, y, coef = create_dataset()
# 2- 训练模型
train(x, y, coef)

第1轮迭代，总损失为:  1021.39173
第2轮迭代，总损失为:  1121.77366
第3轮迭代，总损失为:  1085.40471
第4轮迭代，总损失为:  1069.27768
第5轮迭代，总损失为:  1114.70541
第6轮迭代，总损失为:  1114.64967
第7轮迭代，总损失为:  1101.68219
第8轮迭代，总损失为:  1092.50903
第9轮迭代，总损失为:  1085.86407
第10轮迭代，总损失为:  1094.15986
第11轮迭代，总损失为:  1085.37984
第12轮迭代，总损失为:  1083.20858
第13轮迭代，总损失为:  1082.57061
第14轮迭代，总损失为:  1096.89361
第15轮迭代，总损失为:  1095.66063
第16轮迭代，总损失为:  1093.06621
第17轮迭代，总损失为:  1088.49383
第18轮迭代，总损失为:  1089.46782
第19轮迭代，总损失为:  1093.28632
第20轮迭代，总损失为:  1096.52794
第21轮迭代，总损失为:  1094.31942
第22轮迭代，总损失为:  1095.74910
第23轮迭代，总损失为:  1092.99043
第24轮迭代，总损失为:  1089.73531
第25轮迭代，总损失为:  1095.10833
第26轮迭代，总损失为:  1093.91439
第27轮迭代，总损失为:  1092.59995
第28轮迭代，总损失为:  1098.36422
第29轮迭代，总损失为:  1097.34663
第30轮迭代，总损失为:  1098.56992
第31轮迭代，总损失为:  1100.58281
第32轮迭代，总损失为:  1097.64664
第33轮迭代，总损失为:  1095.43482
第34轮迭代，总损失为:  1095.90933
第35轮迭代，总损失为:  1094.19313
第36轮迭代，总损失为:  1093.57557
第37轮迭代，总损失为:  1093.06372
第38轮迭代，总损失为:  1093.44713
第39轮迭代，总损失为:  1093.35450
第40轮迭代，总损失为:  1094.19978
第41轮迭代，总损